#!/usr/bin/env bash

set -e
set -u

shopt -s globstar
shopt -s extglob

usage() {
	echo "Incorrect usage"
	exit 1
}

serial=false

while test $# != 0
do
	case "$1" in
		-serial)
			serial=true
			;;
		-prod)
			read -p "Enter \"prod\" to continue: " -r
			if [ "$REPLY" != "prod" ]
			then
				echo "Ok, not doing anything"
				exit 1
			fi
			export GITHUB_ORG=go-modules-by-example
			export GITHUB_ORG_ARCHIVE=go-modules-by-example-archive mdreplace
			;;
		--) shift; break;;
		[^-]*) break;;
		*)  usage ;;
	esac
	shift
done

dir=$(git rev-parse --show-toplevel)

if [ "$#" == "0" ]
then
	args="$(ls !(001_go_modules_tour)/README.md *.md | grep -v buffalo)"
else
	args="$*"
fi

if [ "$serial" == "true" ]
then
	for i in $args
	do
		echo Regen $i
		gobin -m -run myitcv.io/cmd/mdreplace -w -long -online $i
	done
else
	gobin -m -run myitcv.io/cmd/mdreplace -w -long -online $args
fi

